Run("winzip26.exe")
;~ WinWaitActive("HTMLUI", "Welcome")
;~ Send("!s")
;~ Sleep(3000)
;~ WinWaitActive("WinZip Setup", "into the following folder")
;~ Send("{ENTER}")
;~ Sleep(3000)
;~ WinWaitActive("WinZip Setup", "WinZip features include")
;~ Send("!n")
;~ Sleep(3000)
;~ WinWaitActive("License Agreement")
;~ Send("!y")
;~ Sleep(3000)
;~ WinWaitActive("WinZip Setup", "Quick Start Guide")
;~ Send("!n")
;~ Sleep(3000)
;~ WinWaitActive("WinZip Setup", "switch between the two interfaces")
;~ Send("!c")
;~ Send("!n")
;~ Sleep(3000)
;~ WinWaitActive("WinZip Setup", "&Express setup (recommended)")
;~ Send("!e")
;~ Send("!n")
;~ Sleep(3000)
;~ WinWaitActive("WinZip Setup", "WinZip needs to associate itself with your archives")
;~ Send("!n")
;~ Sleep(3000)
;~ WinWaitActive("WinZip Setup", "Thank you for installing this evaluation version")
;~ Send("{ENTER}")
;~ Sleep(3000)
;~ WinWaitActive("WinZip (Evaluation Version)")
;~ WinClose("WinZip (Evaluation Version)")